// ─── Theme & Provider ──────────────────────────────────────────
export {
  NativeUIProvider,
  useTheme,
  useColors,
  useThemeColors,
  useSemantic,
  THEME_VARIANTS,
  defaultThemeVariant,
  bloomThemeVariant,
  resolveThemeVariant,
} from './theme';
export type { Theme, NativeUIConfig, ThemeVariant, ThemeVariantName } from './theme';

// ─── Design Tokens ─────────────────────────────────────────────
export {
  colors,
  resolveColorScheme,
  getContrastText,
  THEME_PRESETS,
  defaultColorPalette,
  bloomColorPalette,
  BLOOM_PRESETS,
  typography,
  compactTypography,
  resolveTypography,
  DEFAULT_TYPOGRAPHY_DENSITY,
  systemFontFamilies,
  spaceGroteskFontFamilies,
  bloomFontFamilies,
  FONT_SCALE,
  spacing,
  borderRadius,
  iconSize,
  hitSlop,
  elevation,
  duration,
  zIndex,
  opacity,
  borderWidth,
  easing,
  glowShadow,
  defaultSemanticTokens,
  defaultSemanticColors,
  defaultSemanticSpacing,
  defaultSemanticTypography,
  getResponsiveSpacing,
  getBreakpoint,
  BREAKPOINTS,
} from './tokens';
export type {
  ColorScheme,
  SemanticColor,
  ThemeColors,
  ThemePreset,
  BloomPreset,
  ThemePresetConfig,
  ColorPalette,
  TextRamp,
  SemanticRamp,
  NeutralRamp,
  FontColor,
  ResolveColorOptions,
  TypographyVariant,
  TypographyDensity,
  FontSize,
  Spacing,
  BorderRadius,
  BorderRadiusScale,
  IconSize,
  Elevation,
  ElevationScale,
  SemanticTokens,
  SemanticColorTokens,
  SemanticSpacingTokens,
  SemanticTypographyTokens,
  ResponsiveSpacing,
  Breakpoint,
} from './tokens';

// ─── Utilities ─────────────────────────────────────────────────
export { configureHaptics, getHaptics, parseDecimalInput } from './utils';
export type { HapticsInterface } from './utils';

// ─── Hooks ─────────────────────────────────────────────────────
export { useResponsiveSpacing } from './hooks';

// ─── Primitives ────────────────────────────────────────────────
export {
  Box,
  VStack,
  HStack,
  Text,
  Heading,
  Divider,
  PressableScale,
  usePressableScale,
  MarqueeText,
  PaginationDots,
  SectionLabel,
} from './primitives';
export type {
  BoxProps,
  VStackProps,
  HStackProps,
  StackBaseProps,
  TextProps,
  HeadingProps,
  DividerProps,
  PressableScaleProps,
  UsePressableScaleOptions,
  MarqueeTextProps,
  PaginationDotsProps,
  SectionLabelProps,
} from './primitives';

// ─── Components ────────────────────────────────────────────────
export {
  Button,
  IconButton,
  Card,
  FieldLabel,
  FieldError,
  Input,
  TextArea,
  Select,
  Checkbox,
  Switch,
  Radio,
  Chip,
  ChipGroup,
  Badge,
  Avatar,
  Modal,
  BottomSheet,
  Toast,
  useToast,
  toast,
  ProgressBar,
  Skeleton,
  SkeletonCard,
  SearchBar,
  EmptyState,
  Spinner,
  ListItem,
  ListSection,
  ListSwitchItem,
  ListHeader,
  Section,
  ScreenContainer,
  SettingsRow,
  SettingsSwitchRow,
  InputPrompt,
  HeaderBar,
  BottomTabBar,
  ErrorBoundary,
  withErrorBoundary,
  ConfettiOverlay,
  StatTile,
  ActionTile,
  Countdown,
  DatePickerInput,
  DateRangePickerInput,
} from './components';
export type {
  ButtonProps,
  ButtonVariant,
  ButtonSize,
  IconButtonProps,
  IconButtonVariant,
  IconButtonSize,
  CardProps,
  FieldLabelProps,
  FieldErrorProps,
  InputProps,
  TextAreaProps,
  SelectProps,
  SelectOption,
  SelectTriggerProps,
  SelectOptionItemProps,
  CheckboxProps,
  SwitchProps,
  RadioProps,
  ChipProps,
  ChipGroupProps,
  ChipShape,
  BadgeProps,
  BadgeVariant,
  AvatarProps,
  AvatarSize,
  ModalProps,
  ModalHeaderProps,
  ModalBodyProps,
  ModalFooterProps,
  BottomSheetProps,
  BottomSheetHeaderProps,
  BottomSheetBodyProps,
  BottomSheetFooterProps,
  ToastProps,
  ToastConfig,
  ToastVariant,
  ToastPosition,
  ProgressBarProps,
  ProgressBarColor,
  SkeletonProps,
  SkeletonCardProps,
  SearchBarProps,
  EmptyStateProps,
  SpinnerProps,
  ListItemProps,
  ListSectionProps,
  ListSwitchItemProps,
  ListHeaderProps,
  ListHeaderTransform,
  ListHeaderSize,
  SectionProps,
  ScreenContainerProps,
  SettingsRowProps,
  SettingsSwitchRowProps,
  InputPromptProps,
  HeaderBarProps,
  BottomTabBarProps,
  BottomTabBarItem,
  ErrorBoundaryProps,
  ConfettiOverlayProps,
  StatTileProps,
  StatTileTone,
  StatTileSize,
  ActionTileProps,
  ActionTileTone,
  CountdownProps,
  CountdownFormat,
  DatePickerInputProps,
  DatePickerMode,
  DateRangePickerInputProps,
  DateRangeValue,
} from './components';
