import React from 'react';
import type { Decorator, Loader, Preview } from '@storybook/react';
import { NativeUIProvider, useTheme, type NativeUIConfig } from '@polprog/native-ui';
import { initialize, mswLoader } from 'msw-storybook-addon';
import { nativeTheme } from './theme';
import { fontsReady } from './fonts';
import { defaultHandlers } from './msw/handlers';
import {
  LOCALES,
  LOCALE_LABELS,
  RTL_LOCALES,
  StoryLocaleProvider,
  type StoryLocale,
} from './storyI18n';

/**
 * Initialize MSW once per preview bootstrap. Worker script lives in
 * `apps/storybook/public/mockServiceWorker.js` (checked in, generated by
 * `npx msw init`). `onUnhandledRequest: 'bypass'` keeps Storybook's own
 * asset requests (fonts, docs, icons) free from MSW noise.
 */
if (typeof window !== 'undefined') {
  initialize(
    {
      onUnhandledRequest: 'bypass',
      serviceWorker: { url: '/mockServiceWorker.js' },
    },
    defaultHandlers,
  );
}

type ColorMode = NonNullable<NativeUIConfig['colorMode']>;
type Preset = NonNullable<NativeUIConfig['preset']>;
type FontSize = NonNullable<NativeUIConfig['fontSize']>;
type ThemeGlobal = ColorMode | 'side-by-side';

/**
 * Storybook loader: runs *before* the story and its decorators render.
 * Awaiting `fontsReady` here blocks every mount - including every Canvas
 * inside <Stories /> on Docs pages - until all Space Grotesk weights
 * have actually loaded.
 *
 * Why a loader rather than a per-story <FontGate> or a top-level await
 * at module scope:
 *   - A per-story gate renders a placeholder div with near-zero height;
 *     @storybook/blocks' Canvas measures its child once at mount and
 *     locks its container to that height. When the gate flips, the
 *     real content overflows the cached height → the classic
 *     "rozjechane Stories" glitch that fixes itself on F5 (fonts
 *     cached → synchronous resolution → first measure correct).
 *   - A top-level `await` in preview.tsx breaks Storybook's Rollup
 *     build pipeline for the preview bundle.
 *   - A loader is officially supported, runs once per story render,
 *     and after the first story the promise is already resolved so the
 *     `await` is a single microtask - zero perceptible overhead.
 */
const awaitFonts: Loader = async () => {
  await fontsReady;
  return {};
};

/**
 * Keep our Docs-canvas overflow override the *last* stylesheet in <head>.
 *
 * @storybook/blocks injects Emotion rules (e.g. `overflow: auto` on the
 * Docs Canvas/Story containers) *after* our preview-head.html <style>
 * when Storybook does client-side navigation between Docs pages. At
 * equal specificity the later rule wins → stories render with an inner
 * scroll ("rozjechane") until a hard refresh pushes our rules back to
 * the end. A small, single MutationObserver re-appends the tag whenever
 * new stylesheets are inserted.
 */
const OVERRIDE_STYLE_ID = 'native-ui-docs-overflow-fix';
const OVERRIDE_CSS = `
  .sb-show-main .docs-story,
  .sb-show-main .docs-story > div,
  .sb-show-main .sbdocs-preview { overflow: visible !important; }
`;

if (typeof document !== 'undefined') {
  let overrideEl = document.getElementById(OVERRIDE_STYLE_ID) as HTMLStyleElement | null;
  if (!overrideEl) {
    overrideEl = document.createElement('style');
    overrideEl.id = OVERRIDE_STYLE_ID;
    overrideEl.textContent = OVERRIDE_CSS;
    document.head.appendChild(overrideEl);
  }

  let reAppending = false;
  const observer = new MutationObserver(() => {
    if (reAppending) return;
    if (document.head.lastElementChild !== overrideEl) {
      reAppending = true;
      document.head.appendChild(overrideEl!);
      reAppending = false;
    }
  });
  observer.observe(document.head, { childList: true });
}

/**
 * Container that reads the current theme and paints itself with the live
 * background colour, so dark mode and preset switches don't leave the canvas
 * stuck on a hardcoded hex. Typography/fontFamily is intentionally NOT set
 * here - it should inherit from NativeUIProvider so token changes propagate.
 *
 * `padding` (default 20) adds breathing room between the themed surface and
 * the story content so compact stories (a single row / tile) don't sit
 * flush against the panel edge. Stories that want full-bleed (HeaderBar,
 * BottomTabBar, ScreenContainer demos, overlay patterns) opt out via
 * `parameters.canvasPadding: 0`.
 */
const ThemeCanvas = ({
  children,
  label,
  padding = 20,
}: {
  children: React.ReactNode;
  label?: string;
  padding?: number;
}) => {
  const theme = useTheme();
  return (
    <div
      style={{
        backgroundColor: theme.colors.background,
        color: theme.colors.textPrimary,
        borderRadius: 8,
        width: '100%',
      }}
    >
      {label && (
        <div
          style={{
            fontSize: 11,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: 1,
            color: theme.colors.textSecondary,
            padding: '12px 16px 0',
          }}
        >
          {label}
        </div>
      )}
      <div style={{ padding }}>{children}</div>
    </div>
  );
};

const ThemedStory = ({
  Story,
  colorMode,
  preset,
  fontSize,
  highContrast,
  reduceAnimations,
  label,
  padding,
}: {
  Story: React.ComponentType;
  colorMode: ColorMode;
  preset: Preset;
  fontSize: FontSize;
  highContrast: boolean;
  reduceAnimations: boolean;
  label?: string;
  padding?: number;
}) => (
  <NativeUIProvider
    config={{ colorMode, preset, fontSize, highContrast, reduceAnimations }}
  >
    <ThemeCanvas label={label} padding={padding}>
      <Story />
    </ThemeCanvas>
  </NativeUIProvider>
);

/** Decorator that wraps every story in NativeUIProvider + locale context. */
const withNativeUI: Decorator = (Story, context) => {
  const themeGlobal = (context.globals.theme ?? 'light') as ThemeGlobal;
  const preset = (context.globals.preset ?? 'default') as Preset;
  const fontSize = (context.globals.fontSize ?? 'default') as FontSize;
  const highContrast = context.globals.highContrast === 'on';
  const reduceAnimations = context.globals.reduceMotion === 'on';
  const locale = (context.globals.locale ?? 'en') as StoryLocale;
  const canvasPadding =
    typeof context.parameters?.canvasPadding === 'number'
      ? context.parameters.canvasPadding
      : undefined;

  // Best-effort: mirror locale/direction on the Storybook canvas <html>
  // so addons (a11y, docs) and react-native-web text inherit the right
  // lang + direction. Scoped by typeof check so SSR / test-runner do not
  // choke.
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale;
    document.documentElement.dir = RTL_LOCALES.has(locale) ? 'rtl' : 'ltr';
  }

  if (themeGlobal === 'side-by-side') {
    return (
      <StoryLocaleProvider locale={locale}>
        <div style={{ display: 'flex', gap: 16 }}>
          <ThemedStory
            Story={Story}
            colorMode="light"
            preset={preset}
            fontSize={fontSize}
            highContrast={highContrast}
            reduceAnimations={reduceAnimations}
            padding={canvasPadding}
            label="Light"
          />
          <ThemedStory
            Story={Story}
            colorMode="dark"
            preset={preset}
            fontSize={fontSize}
            highContrast={highContrast}
            reduceAnimations={reduceAnimations}
            padding={canvasPadding}
            label="Dark"
          />
        </div>
      </StoryLocaleProvider>
    );
  }

  return (
    <StoryLocaleProvider locale={locale}>
      <NativeUIProvider
        config={{
          colorMode: themeGlobal,
          preset,
          fontSize,
          highContrast,
          reduceAnimations,
        }}
      >
        <ThemeCanvas padding={canvasPadding}>
          <Story />
        </ThemeCanvas>
      </NativeUIProvider>
    </StoryLocaleProvider>
  );
};

const preview: Preview = {
  loaders: [awaitFonts, mswLoader],
  decorators: [withNativeUI],

  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /date$/i,
      },
      sort: 'requiredFirst',
    },
    docs: {
      theme: nativeTheme,
      // Render every story inline in Docs (no fixed-height iframe wrapper
      // that caused "collapsed with inner scroll" on tall stories).
      story: { inline: true },
      // Source snippet collapsed by default; users expand it on demand.
      source: { state: 'closed', type: 'dynamic', excludeDecorators: true },
      canvas: { sourceState: 'hidden' },
    },
    // `padded` keeps Storybook's outer padding (~1rem). The inner ThemeCanvas
    // adds an additional 20px of breathing room so compact stories (single
    // rows, single components) don't hug the canvas edge. Stories that need
    // full-bleed (HeaderBar, BottomTabBar, ScreenContainer, overlay demos)
    // opt out with `parameters.canvasPadding: 0`.
    layout: 'padded',
    backgrounds: {
      disable: true,
    },
    a11y: {
      // `violation` fails the test run on actual a11y breakage; 'todo' keeps
      // the report visible in the panel without blocking CI.
      config: {
        rules: [
          // react-native-web renders some absolute-positioned overlays
          // outside the story root; this rule generates noisy false positives
          // for those portals.
          { id: 'region', enabled: false },
        ],
      },
      options: {},
    },
    viewport: {
      viewports: {
        // ── Small / legacy ──
        iphoneSE: { name: 'iPhone SE', styles: { width: '375px', height: '667px' } },
        // ── Modern iPhones ──
        iphone13: { name: 'iPhone 13', styles: { width: '390px', height: '844px' } },
        iphone15Pro: {
          name: 'iPhone 15 Pro',
          styles: { width: '393px', height: '852px' },
        },
        iphone16ProMax: {
          name: 'iPhone 16 Pro Max',
          styles: { width: '440px', height: '956px' },
        },
        // ── Modern Android ──
        pixel6: { name: 'Pixel 6', styles: { width: '412px', height: '915px' } },
        pixel8Pro: { name: 'Pixel 8 Pro', styles: { width: '448px', height: '998px' } },
        galaxyS24: {
          name: 'Galaxy S24',
          styles: { width: '384px', height: '832px' },
        },
        // ── Tablets ──
        ipadMini: { name: 'iPad mini', styles: { width: '768px', height: '1024px' } },
        ipad13: { name: 'iPad Pro 13"', styles: { width: '1032px', height: '1376px' } },
        pixelTablet: {
          name: 'Pixel Tablet',
          styles: { width: '840px', height: '1200px' },
        },
      },
    },
    options: {
      storySort: {
        order: [
          'Introduction',
          'Getting Started',
          'Changelog',
          'Theming',
          'Tokens',
          ['Colors', 'Typography', 'Spacing & Radii', 'Spacing', 'Radius & Elevation', 'SemanticTokens'],
          'Brand',
          'Primitives',
          [
            'Box',
            'Stack',
            'Text',
            'Heading',
            'SectionLabel',
            'Divider',
            'PressableScale',
            'MarqueeText',
            'PaginationDots',
          ],
          'Components',
          [
            // Inputs & controls
            'Button',
            'IconButton',
            'Input',
            'TextArea',
            'Select',
            'Checkbox',
            'Switch',
            'Radio',
            'SearchBar',
            // Data display
            'Card',
            'Chip',
            'Badge',
            'Avatar',
            'ProgressBar',
            'Skeleton',
            'EmptyState',
            'Spinner',
            // Lists
            'ListItem',
            'ListSection',
            'ListSwitchItem',
            'ListHeader',
            'Section',
            'SettingsRow',
            // Layout / chrome
            'HeaderBar',
            'ScreenContainer',
            // Overlays
            'Modal',
            'BottomSheet',
            'Toast',
            'InputPrompt',
            'ConfettiOverlay',
            // Utility
            'ErrorBoundary',
          ],
          'Patterns',
          [
            'AppShell',
            'Forms',
            'Lists & Data',
            'Settings',
            'Dialogs & Sheets',
            'Loading States',
            'Web Compatibility',
            'Platform Aware',
          ],
          'Migration',
          'Accessibility',
        ],
      },
    },
  },

  globalTypes: {
    theme: {
      description: 'Theme mode',
      defaultValue: 'light',
      toolbar: {
        title: 'Theme',
        icon: 'circlehollow',
        items: [
          { value: 'light', title: 'Light', icon: 'sun' },
          { value: 'dark', title: 'Dark', icon: 'moon' },
          { value: 'side-by-side', title: 'Side by Side', icon: 'sidebar' },
        ],
        dynamicTitle: true,
      },
    },
    preset: {
      name: 'Theme Preset',
      description: 'Select color preset',
      defaultValue: 'default',
      toolbar: {
        title: 'Preset',
        icon: 'paintbrush',
        items: [
          { value: 'default', title: 'Default (Indigo)' },
          { value: 'midnight', title: 'Midnight' },
          { value: 'ocean', title: 'Ocean' },
          { value: 'forest', title: 'Forest' },
          { value: 'sunset', title: 'Sunset' },
          { value: 'rose', title: 'Rose' },
          { value: 'amoled', title: 'AMOLED' },
        ],
        dynamicTitle: true,
      },
    },
    locale: {
      name: 'Locale',
      description: 'UI language (affects Patterns + lang/dir on <html>)',
      defaultValue: 'en',
      toolbar: {
        title: 'Locale',
        icon: 'globe',
        items: LOCALES.map((code) => ({
          value: code,
          title: `${code.toUpperCase()} · ${LOCALE_LABELS[code]}`,
        })),
        dynamicTitle: true,
      },
    },
    fontSize: {
      name: 'Font size',
      description: 'Typography tier (default / medium / large)',
      defaultValue: 'default',
      toolbar: {
        title: 'Font size',
        icon: 'type',
        items: [
          { value: 'default', title: 'Default (100%)' },
          { value: 'medium', title: 'Medium (~115%)' },
          { value: 'large', title: 'Large (~130%)' },
        ],
        dynamicTitle: true,
      },
    },
    highContrast: {
      name: 'High contrast',
      description: 'Toggle high-contrast a11y mode',
      defaultValue: 'off',
      toolbar: {
        title: 'Contrast',
        icon: 'contrast',
        items: [
          { value: 'off', title: 'Normal' },
          { value: 'on', title: 'High contrast' },
        ],
        dynamicTitle: true,
      },
    },
    reduceMotion: {
      name: 'Reduce motion',
      description: 'Disable animations (iOS/Android a11y setting)',
      defaultValue: 'off',
      toolbar: {
        title: 'Motion',
        icon: 'transfer',
        items: [
          { value: 'off', title: 'Motion on' },
          { value: 'on', title: 'Reduce motion' },
        ],
        dynamicTitle: true,
      },
    },
  },

  // Autodocs stays on globally. Imperative overlay demos (Toast, Modal,
  // BottomSheet, InputPrompt, Dialog patterns) opt out via `tags: ['!autodocs']`
  // on their meta so the Docs page doesn't mount several overlay roots on the
  // same page.
  tags: ['autodocs'],
};

export default preview;
